### ISSUE TITLE
Web üzerinde yeni bir buton konularak RPi'ye komut gönderimesi

### ISSUE THREAD

**Issue by ozalpmurat** [emintopal1905/sera#6]
Mesela "fanı kapat" gibi bir düğme olsun. Buna basında RPi'nin GPIO portlarında OUT olarak belirlenmiş bir portun emülatördeki renginin değiştiğini görelim.

**Comment by emintopal1905** [comment]
Web üzerinden buton yardımıyla emulatördeki ışık değiştirme işlemi tamamlandı Hocam.

**Comment by ozalpmurat** [comment]
Hızlısın maşallah
