### ISSUE TITLE
Resimlerin uygulama içine dehil edilmesi gerekmektedir.

### ISSUE THREAD

**Issue by ozalpmurat** [emintopal1905/sera#7]
İnternet olmadığında da resimleri görebilelim :)

**Comment by emintopal1905** [comment]
Hocam öncelikle mutlu yıllara :) her türlü işlemi denedim normal img src="images/logo.png"  adı altında aldığımda site html dosyasına bastığımda resmi görebiliyorum fakat localhosta atıldığında ordaki resmi göremiyorum. http://localhost/user/seraotomasyonu/templates/images/logo.png şeklindede denedim normalde html içesinde açıldığında gösterim sağlanıyor ama localhosta aktarmada sorun yaşıyor. Her şeyi yaptım ama en küçük şeyi beceremedim.

**Comment by ozalpmurat** [comment]
Çözersin sen bu işi de :)

**Comment by emintopal1905** [comment]
Tamamladım hocam. resimler klasörüne localhost'un erişemediğinden oluyormuş. images klasörünü C:\AppServ\www dizinine atarak sorunu çözdüm artık İnternetsiz de resimler görülüyor. Uzantı olarakta html dosyası içinde http://localhost//images/logo.png şeklinde tanımlamayla yapıldı.

**Comment by ozalpmurat** [comment]
Eyvallah, eline sağlık. Sen proje bitti zaman

**Comment by emintopal1905** [comment]
Teşekkür ederim hocam iyi günler.
